# Generated by Django 4.2.2 on 2023-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('API_TOKEN', models.CharField()),
                ('SECRET_KEY', models.CharField()),
                ('is_mainnet', models.BooleanField()),
            ],
        ),
    ]
