# Generated by Django 4.2.2 on 2023-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.CharField(default='https://api-testnet.bybit.com'),
        ),
    ]
