# Generated by Django 4.2.2 on 2024-04-24 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
