# Generated by Django 4.2.2 on 2023-07-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
