# Generated by Django 4.2.2 on 2024-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wsmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsmanager',
            name='error_text',
            field=models.CharField(null=True),
        ),
    ]
