# Generated by Django 4.2.2 on 2023-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('UNIFIED', 'UNIFIED')], default='CONTRACT', max_length=10, null=True),
        ),
    ]
