# Generated by Django 4.2.2 on 2023-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_account_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField()),
            ],
        ),
    ]
