# Generated by Django 4.2.2 on 2024-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_wsmanager_error_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='low_margin_actions',
            field=models.CharField(blank=True, choices=[('alert', 'Только уведомление'), ('off_bots', 'Выключить ботов')], null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='low_margin_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='low_margin_value_type',
            field=models.CharField(blank=True, choices=[('$', '$'), ('%', '%')], default='$', null=True),
        ),
    ]
