# Generated by Django 4.2.2 on 2024-01-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_activebot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exchangeservice'),
        ),
    ]
