# Generated by Django 4.2.2 on 2024-10-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=25, null=True)),
                ('balance', models.CharField(max_length=25)),
                ('available_balance', models.CharField(max_length=25)),
                ('margin', models.CharField(blank=True, max_length=25, null=True)),
                ('un_pnl', models.CharField(max_length=25)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountbalance', to='main.account')),
            ],
        ),
    ]
