# Generated by Django 4.2.2 on 2024-10-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_accountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='API_TOKEN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='SECRET_KEY',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='low_margin_actions',
            field=models.CharField(blank=True, choices=[('alert', 'Только уведомление'), ('off_bots', 'Выключить ботов')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='low_margin_value_type',
            field=models.CharField(blank=True, choices=[('$', '$'), ('%', '%')], default='$', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='url',
            field=models.CharField(default='https://api-testnet.bybit.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='time_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
