# Generated by Django 4.2.2 on 2024-10-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_account_api_token_alter_account_secret_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('side', models.CharField(max_length=25)),
                ('order_id', models.CharField(max_length=50)),
                ('change', models.CharField(max_length=25)),
                ('cash_flow', models.CharField(max_length=25)),
                ('fee', models.CharField(max_length=25)),
                ('transaction_time', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounthistory', to='main.account')),
            ],
        ),
    ]
