# Generated by Django 4.2.2 on 2024-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_accounthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='cash_flow',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='fee',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='side',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
