# Generated by Django 4.2.2 on 2024-11-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_accountbalance_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('UNIFIED', 'UNIFIED')], default='UNIFIED', max_length=10, null=True),
        ),
    ]
