# Generated by Django 4.2.2 on 2024-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='transaction_time',
            field=models.CharField(max_length=30),
        ),
    ]
