# Generated by Django 4.2.2 on 2025-01-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_accounthistory_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='margin_alert_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
