# Generated by Django 4.2.2 on 2025-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_account_margin_alert_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_demonet',
            field=models.BooleanField(null=True),
        ),
    ]
