# Generated by Django 4.2.2 on 2025-01-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_account_is_demonet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_demonet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
