# Generated by Django 4.2.2 on 2024-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_serviceproduct_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
