---
- name: Cloning the repo's branch to a host
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    single_branch: yes
    version: "{{ repo_branch }}"
    key_file: /root/.ssh/deploy_key
