# Generated by Django 4.2.2 on 2024-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttask',
            name='empty_field',
            field=models.BooleanField(default=False),
        ),
    ]
