# Generated by Django 4.2.2 on 2024-12-05 14:33

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_ticketmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ticket_files/', validators=[support.models.validate_file]),
        ),
    ]
