# Generated by Django 4.2.2 on 2024-12-05 20:04

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_ticketmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=support.models.ticket_file_upload_path, validators=[support.models.validate_file]),
        ),
    ]
