# Generated by Django 4.2.2 on 2024-12-09 19:49

from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_ticketmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='file',
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=support.models.ticket_file_upload_path, validators=[support.models.validate_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='support.ticketmessage')),
            ],
        ),
    ]
