# Generated by Django 4.2.2 on 2023-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField()),
                ('countryName', models.CharField()),
                ('zoneName', models.CharField()),
                ('gmtOffset', models.CharField()),
            ],
        ),
    ]
