# Generated by Django 4.2.2 on 2023-08-19 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timezone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
