# Generated by Django 4.2.2 on 2024-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_doccategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctag',
            name='doc_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='documentation.docpage'),
        ),
    ]
