# Generated by Django 4.2.2 on 2024-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_alter_doctag_doc_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctag',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
