# Generated by Django 4.2.2 on 2024-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_alter_doctag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccategory',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='docpage',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='doctag',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='en', max_length=5),
        ),
    ]
