# Generated by Django 4.2.2 on 2024-05-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0015_stephedge_count_ticks_long_and_more'),
        ('main', '0004_alter_whitelistaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField()),
                ('side', models.CharField(null=True)),
                ('qty', models.CharField(null=True)),
                ('cost', models.CharField(null=True)),
                ('entry_price', models.CharField(null=True)),
                ('unrealisedPnl', models.CharField(null=True)),
                ('realisedPnl', models.CharField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.botmodel')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField()),
                ('order_id', models.CharField()),
                ('client_order_id', models.CharField(null=True)),
                ('side', models.CharField(null=True)),
                ('qty', models.CharField(null=True)),
                ('price', models.CharField(null=True)),
                ('avg_price', models.CharField(null=True)),
                ('trigger_price', models.CharField(null=True)),
                ('trigger_direction', models.CharField(null=True)),
                ('status', models.CharField(null=True)),
                ('psn_side', models.CharField(null=True)),
                ('reduceOnly', models.CharField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.botmodel')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.symbol')),
            ],
        ),
    ]
