# Generated by Django 4.2.2 on 2023-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('linear', 'Linear')], max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('positionIdx', models.IntegerField(blank=True, null=True)),
                ('orderType', models.CharField(choices=[('Limit', 'Limit'), ('Market', 'Market')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeInForce', models.CharField(choices=[('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate or Cancel')], max_length=3)),
                ('orderLinkId', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
