# Generated by Django 4.2.2 on 2024-05-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reduceOnly',
            new_name='reduce_only',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='realisedPnl',
            new_name='realised_pnl',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='unrealisedPnl',
            new_name='unrealised_pnl',
        ),
    ]
