# Generated by Django 4.2.2 on 2023-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('linear', 'Linear')], default='linear', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('Limit', 'Limit'), ('Market', 'Market')], default='Market', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeInForce',
            field=models.CharField(choices=[('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate or Cancel')], default='GTC', max_length=3),
        ),
    ]
