# Generated by Django 4.2.2 on 2024-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_reduceonly_order_reduce_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reduce_only',
            field=models.BooleanField(null=True),
        ),
    ]
