# Generated by Django 4.2.2 on 2023-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_category_alter_order_ordertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
