# Generated by Django 4.2.2 on 2023-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='positionIdx',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
