# Generated by Django 4.2.2 on 2023-06-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('orders', '0005_alter_order_positionidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderType',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeInForce',
            field=models.CharField(default='GTC'),
        ),
    ]
