# Generated by Django 4.2.2 on 2023-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_bot_alter_order_category_alter_order_ordertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_take',
            field=models.BooleanField(default=False),
        ),
    ]
