# Generated by Django 4.2.2 on 2023-07-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isLeverage',
            field=models.IntegerField(default=10),
        ),
    ]
