# Generated by Django 4.2.2 on 2023-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_isleverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tpLimitPrice',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
