# Generated by Django 4.2.2 on 2023-07-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_tplimitprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tpLimitPrice',
            new_name='takeProfit',
        ),
    ]
