# Generated by Django 4.2.2 on 2023-08-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_tplimitprice_order_takeprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stopLoss',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='takeProfit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
