# Generated by Django 4.2.2 on 2023-08-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_stoploss_alter_order_takeprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stopLoss',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='takeProfit',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
