# Generated by Django 4.2.2 on 2023-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_stoploss_alter_order_takeprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.CharField(),
        ),
    ]
