# Generated by Django 4.2.2 on 2023-09-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='char_price',
            field=models.CharField(blank=True, null=True),
        ),
    ]
