# Generated by Django 4.2.2 on 2023-10-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_char_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='triggerPrice',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
