# Generated by Django 4.2.2 on 2023-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_triggerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='triggerDirection',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
