# Generated by Django 4.2.2 on 2024-04-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='linear', max_length=10)),
                ('leverage', models.IntegerField(default=10)),
                ('amount_long', models.IntegerField()),
                ('amount_short', models.IntegerField(blank=True, null=True)),
                ('margin_type', models.CharField(blank=True, choices=[('CROSS', 'CROSS'), ('ISOLATED', 'ISOLATED')], default='CROSS', max_length=10)),
                ('work_model', models.CharField(max_length=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('priceScale', models.CharField(max_length=20, null=True)),
                ('minLeverage', models.CharField(max_length=20, null=True)),
                ('maxLeverage', models.CharField(max_length=20, null=True)),
                ('leverageStep', models.CharField(max_length=20, null=True)),
                ('minPrice', models.CharField(max_length=20, null=True)),
                ('maxPrice', models.CharField(max_length=20, null=True)),
                ('tickSize', models.CharField(max_length=20, null=True)),
                ('minOrderQty', models.CharField(max_length=20, null=True)),
                ('maxOrderQty', models.CharField(max_length=20, null=True)),
                ('qtyStep', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exchangeservice')),
            ],
        ),
        migrations.CreateModel(
            name='StepHedge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short1invest', models.CharField(max_length=20, null=True)),
                ('long1invest', models.CharField(max_length=20, null=True)),
                ('tp_pnl_percent', models.CharField(max_length=20, null=True)),
                ('tp_pnl_percent_long', models.CharField(max_length=20, null=True)),
                ('pnl_short_avg', models.CharField(max_length=20, null=True)),
                ('pnl_long_avg', models.CharField(max_length=20, null=True)),
                ('margin_short_avg', models.CharField(max_length=20, null=True)),
                ('margin_long_avg', models.CharField(max_length=20, null=True)),
                ('qty_steps', models.IntegerField(default=30, null=True)),
                ('qty_steps_diff', models.IntegerField(default=10)),
                ('add_tp', models.BooleanField(default=False)),
                ('is_nipple_active', models.BooleanField(default=True)),
                ('move_nipple', models.BooleanField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleHedge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tppp', models.CharField(blank=True, null=True)),
                ('tpap', models.CharField(blank=True, null=True)),
                ('tp_count', models.IntegerField(blank=True, default=1, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Set0Psn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set0psn', models.BooleanField(default=False)),
                ('trend', models.IntegerField(blank=True, null=True)),
                ('limit_pnl_loss_s0n', models.CharField(blank=True, null=True)),
                ('max_margin_s0p', models.CharField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OppositePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_opp', models.BooleanField(default=False)),
                ('limit_pnl_loss_opp', models.CharField(blank=True, null=True)),
                ('psn_qty_percent_opp', models.CharField(blank=True, null=True)),
                ('max_margin_opp', models.CharField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, null=True)),
                ('time', models.CharField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JsonObjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_mode', models.CharField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
        migrations.AddField(
            model_name='botmodel',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.symbol'),
        ),
        migrations.CreateModel(
            name='BBBotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('FB', 'First Band')], default='FB', max_length=4)),
                ('orderType', models.CharField(blank=True, choices=[('Limit', 'Limit'), ('Market', 'Market')], default='Limit', max_length=10)),
                ('qty_kline', models.IntegerField(default=20)),
                ('interval', models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('15', '15'), ('30', '30'), ('60', '60'), ('120', '120'), ('240', '240'), ('360', '360'), ('720', '720'), ('D', 'D'), ('W', 'W'), ('M', 'M')], default='15', max_length=3)),
                ('d', models.IntegerField(default=2)),
                ('take_on_ml', models.BooleanField(default=True)),
                ('take_on_ml_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('auto_avg', models.BooleanField(default=False)),
                ('avg_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_deviation_from_lines', models.BooleanField(blank=True, default=False)),
                ('percent_deviation_from_lines', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('dfm', models.DecimalField(decimal_places=3, default=30, max_digits=5)),
                ('chw', models.DecimalField(decimal_places=3, default=2, max_digits=5)),
                ('dfep', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('max_margin', models.IntegerField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb', to='bots.botmodel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='botmodel',
            unique_together={('account', 'symbol')},
        ),
    ]
