# Generated by Django 4.2.2 on 2023-06-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='d',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='interval',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='qty_kline',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
