# Generated by Django 4.2.2 on 2024-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbotmodel',
            name='take_on_ml_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
