# Generated by Django 4.2.2 on 2024-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbotmodel',
            name='take_on_ml_qty',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bbbotmodel',
            name='take_on_ml_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
