# Generated by Django 4.2.2 on 2023-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_d_bot_interval_bot_qty_kline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
