# Generated by Django 4.2.2 on 2024-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bbbotmodel_take_on_ml_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
