# Generated by Django 4.2.2 on 2024-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_log_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbotmodel',
            name='dfm',
            field=models.DecimalField(decimal_places=3, default=70, max_digits=5),
        ),
    ]
