# Generated by Django 4.2.2 on 2023-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
