# Generated by Django 4.2.2 on 2024-04-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bbbotmodel_dfm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stephedge',
            name='tp_pnl_percent',
        ),
        migrations.AddField(
            model_name='stephedge',
            name='income_percent',
            field=models.DecimalField(decimal_places=1, default=6, max_digits=4),
        ),
        migrations.AddField(
            model_name='stephedge',
            name='tp_pnl_percent_short',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zinger', to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='long1invest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='margin_long_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='margin_short_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='pnl_long_avg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='pnl_short_avg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='qty_steps',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='short1invest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='tp_pnl_percent_long',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
