# Generated by Django 4.2.2 on 2023-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_bot_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='process_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
