# Generated by Django 4.2.2 on 2024-04-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_remove_stephedge_tp_pnl_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stephedge',
            name='qty_steps',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='qty_steps_diff',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
