# Generated by Django 4.2.2 on 2024-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_stephedge_qty_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stephedge',
            name='add_tp',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='is_nipple_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
