# Generated by Django 4.2.2 on 2023-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_bot_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='margin_type',
            field=models.CharField(choices=[('CROSS', 'CROSS'), ('ISOLATED', 'ISOLATED')], default='CROSS', max_length=10),
        ),
    ]
