# Generated by Django 4.2.2 on 2023-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_bot_margin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('linear', 'Linear'), ('spot', 'Spot')], default='linear', max_length=10),
        ),
        migrations.AlterField(
            model_name='bot',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Auto', 'Auto')], default='Buy', max_length=4),
        ),
    ]
