# Generated by Django 4.2.2 on 2024-04-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_stephedge_add_tp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbotmodel',
            name='take_on_ml_qty',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
