# Generated by Django 4.2.2 on 2024-04-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_bbbotmodel_take_on_ml_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='is_nipple_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
