# Generated by Django 4.2.2 on 2023-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_bot_category_alter_bot_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='interval',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('15', '15'), ('30', '30'), ('60', '60'), ('120', '120'), ('240', '240'), ('360', '360'), ('720', '720'), ('D', 'D'), ('M', 'M'), ('W', 'W')], default='15', max_length=3),
        ),
    ]
