# Generated by Django 4.2.2 on 2024-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_stephedge_realized_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbotmodel',
            name='hard_avg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bbbotmodel',
            name='hard_avg_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bbbotmodel',
            name='hard_avg_type',
            field=models.CharField(blank=True, choices=[('pnl', 'Убытки (PnL)'), ('percent', 'Изменение цены')], null=True),
        ),
    ]
