# Generated by Django 4.2.2 on 2023-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_alter_bot_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Auto', 'Auto')], default='Auto', max_length=4),
        ),
    ]
