# Generated by Django 4.2.2 on 2023-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_alter_bot_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
