# Generated by Django 4.2.2 on 2024-04-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_bbbotmodel_hard_avg_bbbotmodel_hard_avg_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='tp_trailing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='stephedge',
            name='tp_trailing_percent',
            field=models.CharField(choices=[('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.5', '0.5'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('10', '10')], default='1', max_length=5),
        ),
    ]
