# Generated by Django 4.2.2 on 2024-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_stephedge_tp_trailing_stephedge_tp_trailing_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='reinvest_long',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='stephedge',
            name='reinvest_short',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
