# Generated by Django 4.2.2 on 2023-06-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_url'),
        ('bots', '0011_alter_bot_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.account'),
        ),
    ]
