# Generated by Django 4.2.2 on 2024-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_stephedge_reinvest_long_stephedge_reinvest_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='reinvest_with_leverage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
