# Generated by Django 4.2.2 on 2023-06-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_url'),
        ('bots', '0013_alter_bot_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.account'),
        ),
    ]
