# Generated by Django 4.2.2 on 2024-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_stephedge_reinvest_with_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='reinvest_count_ticks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
