# Generated by Django 4.2.2 on 2023-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_alter_bot_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='work_model',
            field=models.CharField(choices=[('grid', 'grid'), ('BB', 'BB')], default='BB', max_length=10),
        ),
    ]
