# Generated by Django 4.2.2 on 2024-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_stephedge_reinvest_count_ticks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='count_ticks_long',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stephedge',
            name='count_ticks_short',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
