# Generated by Django 4.2.2 on 2024-06-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_stephedge_count_ticks_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbotmodel',
            name='count_cycles',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
