# Generated by Django 4.2.2 on 2023-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_bot_work_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='work_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
