# Generated by Django 4.2.2 on 2023-06-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_alter_bot_work_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bot',
            name='symbol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.symbol'),
        ),
    ]
