# Generated by Django 4.2.2 on 2023-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_symbol_alter_bot_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(default='linear', max_length=10),
        ),
    ]
