# Generated by Django 4.2.2 on 2024-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_bbbotmodel_endless_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbotmodel',
            name='take_after_ml',
            field=models.BooleanField(default=False),
        ),
    ]
