# Generated by Django 4.2.2 on 2023-06-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0019_alter_bot_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.symbol'),
        ),
    ]
