# Generated by Django 4.2.2 on 2024-06-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0019_bbbotmodel_stop_bot_after_loss_bbbotmodel_stop_loss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pnl', models.CharField(blank=True, null=True)),
                ('count_cycles', models.IntegerField(blank=True, null=True)),
                ('cycle_pnl_dict', models.JSONField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
    ]
