# Generated by Django 4.2.2 on 2023-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_alter_bot_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='symbol',
            field=models.CharField(),
        ),
    ]
