# Generated by Django 4.2.2 on 2024-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_botsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='cycle_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
