# Generated by Django 4.2.2 on 2024-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0021_botmodel_cycle_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsdata',
            name='count_cycles',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='botsdata',
            name='cycle_pnl_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='botsdata',
            name='total_pnl',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20),
        ),
    ]
