# Generated by Django 4.2.2 on 2024-06-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_alter_botsdata_count_cycles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('time', models.CharField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
    ]
