# Generated by Django 4.2.2 on 2023-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0023_bot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='leverageStep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='maxLeverage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='maxPrice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='minLeverage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='minOrderQty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='minPrice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='priceScale',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
