# Generated by Django 4.2.2 on 2024-07-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_account_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0024_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
        migrations.AlterField(
            model_name='botmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
