# Generated by Django 4.2.2 on 2023-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0024_symbol_leveragestep_symbol_maxleverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='auto_avg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='bb_avg_percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='bot',
            name='chw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='deviation_from_lines',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='dfm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='grid_avg_value',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='bot',
            name='max_margin',
            field=models.IntegerField(null=True),
        ),
    ]
