# Generated by Django 4.2.2 on 2024-07-31 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0025_alter_botmodel_account_alter_botmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='amount_long',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='botmodel',
            name='amount_short',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='botmodel',
            name='work_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
