# Generated by Django 4.2.2 on 2023-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0025_bot_auto_avg_bot_bb_avg_percent_bot_chw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='dfm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
