# Generated by Django 4.2.2 on 2024-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0026_alter_botmodel_amount_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='grid_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='grid',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
