# Generated by Django 4.2.2 on 2023-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0026_alter_bot_chw_alter_bot_dfm_alter_bot_max_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_percent_deviation_from_lines',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='chw',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='bot',
            name='dfm',
            field=models.IntegerField(default=30),
        ),
    ]
