# Generated by Django 4.2.2 on 2024-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0027_alter_grid_grid_count_alter_grid_high_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='min_notional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
