# Generated by Django 4.2.2 on 2023-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0027_bot_is_percent_deviation_from_lines_alter_bot_chw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='take_on_ml',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='take_on_ml_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
