# Generated by Django 4.2.2 on 2024-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0028_symbol_min_notional'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='conn_status',
            field=models.BooleanField(default=False),
        ),
    ]
