# Generated by Django 4.2.2 on 2023-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0028_bot_take_on_ml_bot_take_on_ml_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='grid_profit_value',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
        ),
    ]
