# Generated by Django 4.2.2 on 2025-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0029_botmodel_conn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='bot_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
