# Generated by Django 4.2.2 on 2023-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0029_bot_grid_profit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='time_sleep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
