# Generated by Django 4.2.2 on 2023-07-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0030_bot_time_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='time_sleep',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
