# Generated by Django 4.2.2 on 2025-01-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0030_botmodel_bot_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsdata',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='bots.botmodel'),
        ),
    ]
