# Generated by Django 4.2.2 on 2023-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0031_alter_bot_time_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='firs_take_is_done',
            field=models.BooleanField(default=False),
        ),
    ]
