# Generated by Django 4.2.2 on 2025-01-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0031_alter_botsdata_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='enabled_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botmodel',
            name='forcibly_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
