# Generated by Django 4.2.2 on 2023-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0032_bot_firs_take_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='deviation_from_lines',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
