# Generated by Django 4.2.2 on 2023-07-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0034_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot'),
        ),
    ]
