# Generated by Django 4.2.2 on 2023-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0035_alter_log_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='entry_order_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='entry_order_sell',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='take1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='take2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
