# Generated by Django 4.2.2 on 2023-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0036_bot_entry_order_by_bot_entry_order_sell_bot_take1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
