# Generated by Django 4.2.2 on 2023-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0037_bot_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
