# Generated by Django 4.2.2 on 2023-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0038_alter_bot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
