# Generated by Django 4.2.2 on 2023-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0039_bot_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='deviation_from_lines',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
