# Generated by Django 4.2.2 on 2023-07-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0041_bot_grid_take_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('linear', 'linear'), ('inverse', 'inverse')], default='linear', max_length=10),
        ),
    ]
