# Generated by Django 4.2.2 on 2023-07-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0044_alter_process_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bots.bot'),
        ),
    ]
