# Generated by Django 4.2.2 on 2023-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0046_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('FB', 'First Band'), ('TS', 'Two-Sided')], default='Auto', max_length=4),
        ),
    ]
