# Generated by Django 4.2.2 on 2023-07-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0047_alter_bot_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_link_id', models.CharField(default='')),
                ('is_filled', models.BooleanField(default=False)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
