# Generated by Django 4.2.2 on 2023-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0048_avgorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='order_link_id',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
