# Generated by Django 4.2.2 on 2023-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0049_alter_take_order_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgorder',
            name='is_filled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='avgorder',
            name='order_link_id',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='take',
            name='is_filled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
