# Generated by Django 4.2.2 on 2023-07-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0050_alter_avgorder_is_filled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.BooleanField(default=False)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
