# Generated by Django 4.2.2 on 2023-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0051_singlebot'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='maxOrderQty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
