# Generated by Django 4.2.2 on 2023-08-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0052_symbol_maxorderqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsTSStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TS', models.BooleanField(default=False)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
