# Generated by Django 4.2.2 on 2023-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0053_istsstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chw',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bot',
            name='dfm',
            field=models.DecimalField(decimal_places=3, default=30, max_digits=5),
        ),
    ]
