# Generated by Django 4.2.2 on 2023-08-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_log'),
        ('bots', '0054_alter_bot_chw_alter_bot_dfm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('account', 'symbol')},
        ),
    ]
