# Generated by Django 4.2.2 on 2023-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0055_alter_bot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='take1_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
