# Generated by Django 4.2.2 on 2023-08-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0056_bot_take1_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='take1_amount',
            new_name='take2_amount',
        ),
    ]
