# Generated by Django 4.2.2 on 2023-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0057_rename_take1_amount_bot_take2_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='entry_order_by_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='entry_order_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
