# Generated by Django 4.2.2 on 2023-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0058_bot_entry_order_by_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
