# Generated by Django 4.2.2 on 2023-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0059_bot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bin_order',
            field=models.BooleanField(default=True),
        ),
    ]
