# Generated by Django 4.2.2 on 2023-08-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0060_bot_bin_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bin_order_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
