# Generated by Django 4.2.2 on 2023-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0061_bot_bin_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='dfep',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
