# Generated by Django 4.2.2 on 2023-08-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0062_bot_dfep'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='tickSize',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
