# Generated by Django 4.2.2 on 2023-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0064_alter_bot_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
