# Generated by Django 4.2.2 on 2023-09-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0065_log_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set0Psn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set0psn', models.BooleanField(default=False)),
                ('limit_pnl', models.CharField()),
                ('max_margin', models.CharField()),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
