# Generated by Django 4.2.2 on 2023-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0066_set0psn'),
    ]

    operations = [
        migrations.AddField(
            model_name='set0psn',
            name='trend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set0psn',
            name='limit_pnl',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set0psn',
            name='max_margin',
            field=models.CharField(blank=True, null=True),
        ),
    ]
