# Generated by Django 4.2.2 on 2023-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0067_set0psn_trend_alter_set0psn_limit_pnl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.bot'),
        ),
    ]
