# Generated by Django 4.2.2 on 2023-09-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0068_alter_log_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleHedge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tppp', models.CharField(blank=True, null=True)),
                ('tpap', models.CharField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
