# Generated by Django 4.2.2 on 2023-09-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0069_simplehedge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.bot'),
        ),
    ]
