# Generated by Django 4.2.2 on 2023-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0070_alter_log_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('linear', 'linear'), ('inverse', 'inverse')], default='linear', max_length=10),
        ),
    ]
