# Generated by Django 4.2.2 on 2023-10-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0071_alter_bot_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set0psn',
            old_name='max_margin',
            new_name='max_margin_s0p',
        ),
    ]
