# Generated by Django 4.2.2 on 2023-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0072_rename_max_margin_set0psn_max_margin_s0p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
