# Generated by Django 4.2.2 on 2023-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0073_alter_bot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplehedge',
            name='tp_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
