# Generated by Django 4.2.2 on 2023-10-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0074_simplehedge_tp_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppositePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('limit_pnl', models.CharField(blank=True, null=True)),
                ('max_margin', models.CharField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
