# Generated by Django 4.2.2 on 2023-10-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0075_oppositeposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oppositeposition',
            old_name='activate',
            new_name='activate_opp',
        ),
        migrations.RenameField(
            model_name='oppositeposition',
            old_name='limit_pnl',
            new_name='limit_pnl_loss_opp',
        ),
        migrations.RenameField(
            model_name='oppositeposition',
            old_name='max_margin',
            new_name='max_margin_opp',
        ),
        migrations.RenameField(
            model_name='set0psn',
            old_name='limit_pnl',
            new_name='limit_pnl_loss_s0n',
        ),
    ]
