# Generated by Django 4.2.2 on 2023-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0076_rename_activate_oppositeposition_activate_opp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppositeposition',
            name='psn_qty_percent_opp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
