# Generated by Django 4.2.2 on 2023-10-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0077_oppositeposition_psn_qty_percent_opp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepHedge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short1invest', models.CharField(blank=True, null=True)),
                ('long1invest', models.CharField(blank=True, null=True)),
                ('tp_pnl_percent', models.CharField(blank=True, null=True)),
                ('pnl_short_avg', models.CharField(blank=True, null=True)),
                ('pnl_long_avg', models.CharField(blank=True, null=True)),
                ('margin_short_avg', models.CharField(blank=True, null=True)),
                ('margin_long_avg', models.CharField(blank=True, null=True)),
                ('qty_steps', models.CharField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
