# Generated by Django 4.2.2 on 2023-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0078_stephedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='qtyStep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
