# Generated by Django 4.2.2 on 2023-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0079_symbol_qtystep'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='qty_steps_diff',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='long1invest',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='margin_long_avg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='margin_short_avg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='pnl_long_avg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='pnl_short_avg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='qty_steps',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='short1invest',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='tp_pnl_percent',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
