# Generated by Django 4.2.2 on 2023-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0080_stephedge_qty_steps_diff_alter_stephedge_long1invest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='add_tp',
            field=models.BooleanField(default=False),
        ),
    ]
