# Generated by Django 4.2.2 on 2023-11-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0081_stephedge_add_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
