# Generated by Django 4.2.2 on 2023-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0082_log_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='is_nipple_active',
            field=models.BooleanField(default=True),
        ),
    ]
