# Generated by Django 4.2.2 on 2023-11-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0083_stephedge_is_nipple_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonObjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_mode', models.CharField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
