# Generated by Django 4.2.2 on 2023-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0084_jsonobjectclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='move_nipple',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
