# Generated by Django 4.2.2 on 2023-12-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots_group', '0001_initial'),
        ('bots', '0086_bot_time_create_bot_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots_group.botsgroup'),
        ),
    ]
