# Generated by Django 4.2.2 on 2023-12-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots_group', '0001_initial'),
        ('bots', '0087_bot_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots_group.botsgroup'),
        ),
    ]
