# Generated by Django 4.2.2 on 2023-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0088_alter_bot_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephedge',
            name='tp_pnl_percent_long',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
