# Generated by Django 4.2.2 on 2024-01-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0089_stephedge_tp_pnl_percent_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.exchangeservice'),
        ),
    ]
