# Generated by Django 4.2.2 on 2024-01-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_account_service'),
        ('bots', '0091_alter_bot_service_delete_exchangeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exchangeservice'),
        ),
    ]
