# Generated by Django 4.2.2 on 2024-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_symbol_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='interval',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('15', '15'), ('30', '30'), ('60', '60'), ('120', '120'), ('240', '240'), ('360', '360'), ('720', '720'), ('D', 'D'), ('W', 'W'), ('M', 'M')], default='15', max_length=3),
        ),
        migrations.AlterField(
            model_name='bot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
