# Generated by Django 4.2.2 on 2024-03-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0095_bollingerbandsbotmodel_botmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BollingerBandsBotModel',
            new_name='BBBotModel',
        ),
    ]
