# Generated by Django 4.2.2 on 2024-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0097_alter_bbbotmodel_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='margin_type',
            field=models.CharField(blank=True, choices=[('CROSS', 'CROSS'), ('ISOLATED', 'ISOLATED')], default='CROSS', max_length=10),
        ),
    ]
