# Generated by Django 4.2.2 on 2024-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0098_alter_botmodel_margin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbotmodel',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('FB', 'First Band')], default='FB', max_length=4),
        ),
    ]
