# Generated by Django 4.2.2 on 2024-03-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0100_alter_bbbotmodel_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botmodel'),
        ),
    ]
