# Generated by Django 4.2.2 on 2024-03-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0101_alter_log_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgorder',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='istsstart',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='jsonobjectclass',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='oppositeposition',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='process',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='set0psn',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='simplehedge',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='singlebot',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='stephedge',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
        migrations.AlterField(
            model_name='take',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel'),
        ),
    ]
