# Generated by Django 4.2.2 on 2024-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0102_alter_avgorder_bot_alter_istsstart_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbotmodel',
            name='is_deviation_from_lines',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bbbotmodel',
            name='percent_deviation_from_lines',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
        ),
    ]
