# Generated by Django 4.2.2 on 2024-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='response_time_from_support',
            field=models.IntegerField(default=7),
        ),
    ]
