# Generated by Django 4.2.2 on 2024-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_price_alter_tariff_response_time_from_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVED', 'ARCHIVED'), ('ADMIN', 'ADMIN')], default='inactive', null=True),
        ),
    ]
