# Generated by Django 4.2.2 on 2024-10-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVED', 'ARCHIVED'), ('ADMIN', 'ADMIN')], default='INACTIVE', null=True),
        ),
    ]
