# Generated by Django 4.2.2 on 2024-10-16 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tariffs', '0004_alter_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertariff',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
