# Generated by Django 4.2.2 on 2024-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_alter_usertariff_tariff_alter_usertariff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVED', 'ARCHIVED'), ('ADMIN', 'ADMIN')], default='INACTIVE', max_length=25, null=True),
        ),
    ]
