# Generated by Django 4.2.2 on 2024-11-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0006_alter_tariff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertariff',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
