# Generated by Django 4.2.2 on 2024-11-05 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0007_usertariff_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30), null=True),
        ),
    ]
