# Generated by Django 4.2.2 on 2025-01-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEWS', 'NEWS'), ('ARTICLE', 'ARTICLE'), ('SYMBOL', 'SYMBOL')], max_length=25)),
                ('category', models.CharField(choices=[('COMMON', 'COMMON')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/covers/')),
                ('published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
