# Generated by Django 4.2.2 on 2025-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], max_length=5, null=True),
        ),
    ]
