# Generated by Django 4.2.2 on 2025-01-21 08:41

import articles.models
from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(upload_to=articles.models.article_file_upload_path, validators=[support.models.validate_file]),
        ),
    ]
