# Generated by Django 4.2.2 on 2025-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('NEWS', 'NEWS'), ('ARTICLE', 'ARTICLE'), ('SYMBOL', 'SYMBOL'), ('INDICATOR', 'INDICATOR'), ('BYBIT', 'BYBIT')], max_length=25),
        ),
    ]
